### ISSUE TITLE
Core out of sync in 15Khz CRTs

### ISSUE THREAD

**Issue by maxriptide** [MiSTer-devel/Arcade-Galivan_MiSTer#5]
Dear Pierre,
after last core update (Arcade_Galivan_20221013.rbf), both Ufo Robot Dangar and Galivan does not work on my 15Khz CRTs anymore, video is out-of-sync. I noticed that the refresh rate is 65.4Hz in the latest release, while it was 58.01Hz in the previous release (Arcade_Galivan_20220919.rbf).
I don't know if this refresh rate change was made in order to match the real PCB refresh rate, if it is the case it would be useful to have a menu option to switch to 60Hz to keep CRT compatibility, if possible of course.

**Comment by pcornier** [comment]
I just pushed a new release with correct video timings. Can you check if it's working now? For me, it works well on my CRTs. Thank you!

**Comment by maxriptide** [comment]
I confirm that the new core release (Arcade-Galivan_20221103.rbf) is working well on my 15khz CRTs.
Thanks! :-)
